#!/bin/bash

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000000
HISTFILESIZE=1000000

export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

## RDKit ENV variables
export INDIGOBASE=/opt/indigo
export PYTHONPATH=$INDIGOBASE:$PYTHONPATH
#source virtualenvwrapper.sh

