#!/bin/bash

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000000
HISTFILESIZE=1000000

export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

## RDKit ENV variables
export RDBASE=/home/chembl/rdkit
export INDIGOBASE=/home/chembl/indigo
export LD_LIBRARY_PATH=$RDBASE/lib:$LD_LIBRARY_PATH
export PYTHONPATH=$RDBASE:$INDIGOBASE:$PYTHONPATH
#source virtualenvwrapper.sh

